---
dist: trusty
sudo: false
language: php
addons:
  chrome: stable
services:
  - mysql
before_script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  - php -S 0.0.0.0:8000
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000s &
  - mysql -e 'CREATE DATABASE 2moons;'
php:
  - '7.0'
install:
  - composer install
env:
  - DB_HOST: localhost
  - DB_USER: travis
  - DB_PASSWORD:
  - DB_NAME: 2moons
  - ADMIN_NAME: admin
  - ADMIN_PASSWORD: admin
  - ADMIN_MAIL: mail@example.com

cache:
  directories:
    - $HOME/.composer/cache/files

script: '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'